# Generated by Django 3.0.7 on 2020-06-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200618_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lat', 'lon')},
        ),
    ]
