# Generated by Django 3.0.7 on 2020-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ImageField(upload_to='places/%Y/%m', verbose_name='Image'),
        ),
    ]
