# Generated by Django 3.0.7 on 2020-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200620_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(blank=True, max_length=1000, verbose_name='short description'),
        ),
    ]
