# Generated by Django 3.0.7 on 2020-07-04 17:48

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import server.apps.places.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(upload_to='places/%Y/%m', verbose_name='Image location')),
                ('_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description_short', models.CharField(blank=True, max_length=1000, verbose_name='short description')),
                ('description_long', tinymce.models.HTMLField(verbose_name='description')),
                ('coord', server.apps.places.fields.PointField(verbose_name='coordinates (lng, lat)')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=django.contrib.postgres.indexes.GistIndex(fields=['coord'], name='places_plac_coord_d56830_gist'),
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
